
import java.awt.*;

/**
 *
 * @author Nfax1
 */
public class Calc extends javax.swing.JFrame {
    
    /**
     * Creates new form Calc
     */
    public Calc() {
        initComponents();
        
        buAns.setBackground(Color.yellow);
        
        bu1.setBackground(Color.black);
        bu1.setForeground(Color.white);
        bu2.setBackground(Color.black);
        bu2.setForeground(Color.white);
        bu3.setBackground(Color.black);
        bu3.setForeground(Color.white);
        bu4.setBackground(Color.black);
        bu4.setForeground(Color.white);
        bu5.setBackground(Color.black);
        bu5.setForeground(Color.white);
        bu6.setBackground(Color.black);
        bu6.setForeground(Color.white);
        bu7.setBackground(Color.black);
        bu7.setForeground(Color.white);
        bu8.setBackground(Color.black);
        bu8.setForeground(Color.white);
        bu9.setBackground(Color.black);
        bu9.setForeground(Color.white);
        bu0.setBackground(Color.black);
        bu0.setForeground(Color.white);
        
        buAdd.setBackground(Color.gray);
        buAdd.setBackground(Color.white);
        buSub.setBackground(Color.gray);
        buSub.setBackground(Color.white);
        buMultiply.setBackground(Color.gray);
        buMultiply.setBackground(Color.white);
        buDivide.setBackground(Color.gray);
        buDivide.setBackground(Color.white);
        
        buDel.setBackground(Color.darkGray);
        buDel.setBackground(Color.white);
        buC.setBackground(Color.darkGray);
        buC.setBackground(Color.white);
        
        buDecimal.setBackground(Color.orange);
        buDecimal.setForeground(Color.black);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tf = new javax.swing.JTextField();
        bu9 = new javax.swing.JButton();
        buAns = new javax.swing.JButton();
        buOpenParen = new javax.swing.JButton();
        bu7 = new javax.swing.JButton();
        bu8 = new javax.swing.JButton();
        bu5 = new javax.swing.JButton();
        bu6 = new javax.swing.JButton();
        bu4 = new javax.swing.JButton();
        bu2 = new javax.swing.JButton();
        bu3 = new javax.swing.JButton();
        bu1 = new javax.swing.JButton();
        bu0 = new javax.swing.JButton();
        buDecimal = new javax.swing.JButton();
        buDel = new javax.swing.JButton();
        buC = new javax.swing.JButton();
        buAdd = new javax.swing.JButton();
        buSub = new javax.swing.JButton();
        buMultiply = new javax.swing.JButton();
        buDivide = new javax.swing.JButton();
        buClosedParen = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CALCULATOR");

        tf.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tf.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfActionPerformed(evt);
            }
        });

        bu9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bu9.setText("9");
        bu9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bu9ActionPerformed(evt);
            }
        });

        buAns.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        buAns.setText("ANS");
        buAns.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buAnsActionPerformed(evt);
            }
        });

        buOpenParen.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        buOpenParen.setText("(");
        buOpenParen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buOpenParenActionPerformed(evt);
            }
        });

        bu7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bu7.setText("7");
        bu7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bu7ActionPerformed(evt);
            }
        });

        bu8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bu8.setText("8");
        bu8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bu8ActionPerformed(evt);
            }
        });

        bu5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bu5.setText("5");
        bu5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bu5ActionPerformed(evt);
            }
        });

        bu6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bu6.setText("6");
        bu6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bu6ActionPerformed(evt);
            }
        });

        bu4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bu4.setText("4");
        bu4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bu4ActionPerformed(evt);
            }
        });

        bu2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bu2.setText("2");
        bu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bu2ActionPerformed(evt);
            }
        });

        bu3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bu3.setText("3");
        bu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bu3ActionPerformed(evt);
            }
        });

        bu1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bu1.setText("1");
        bu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bu1ActionPerformed(evt);
            }
        });

        bu0.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bu0.setText("0");
        bu0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bu0ActionPerformed(evt);
            }
        });

        buDecimal.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        buDecimal.setText(".");
        buDecimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buDecimalActionPerformed(evt);
            }
        });

        buDel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        buDel.setText("DEL");
        buDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buDelActionPerformed(evt);
            }
        });

        buC.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        buC.setText("C");
        buC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buCActionPerformed(evt);
            }
        });

        buAdd.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        buAdd.setText("+");
        buAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buAddActionPerformed(evt);
            }
        });

        buSub.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        buSub.setText("-");
        buSub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buSubActionPerformed(evt);
            }
        });

        buMultiply.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        buMultiply.setText("x");
        buMultiply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buMultiplyActionPerformed(evt);
            }
        });

        buDivide.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        buDivide.setText("/");
        buDivide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buDivideActionPerformed(evt);
            }
        });

        buClosedParen.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        buClosedParen.setText(")");
        buClosedParen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buClosedParenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tf)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(buOpenParen, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buClosedParen, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buDel, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(buAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(buSub, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(buMultiply, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(buDivide, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(bu7, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(bu8, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(bu9, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(bu4, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(bu5, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(bu6, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(bu1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(bu2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(bu3, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bu0, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buDecimal, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buAns, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buC, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(75, 75, 75)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(tf, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buAns, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bu9, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bu8, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bu7, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bu6, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bu5, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bu4, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bu3, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bu2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bu1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(buAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(buOpenParen, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buSub, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buClosedParen, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(buMultiply, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(buDivide, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bu0, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(buDecimal, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(buC, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(buDel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfActionPerformed

    private void bu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bu1ActionPerformed
        // TODO add your handling code here:
        tf.setText(tf.getText() + "1");
    }//GEN-LAST:event_bu1ActionPerformed

    private void bu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bu2ActionPerformed
        // TODO add your handling code here:
        tf.setText(tf.getText() + "2");
    }//GEN-LAST:event_bu2ActionPerformed

    private void bu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bu3ActionPerformed
        // TODO add your handling code here:
        tf.setText(tf.getText() + "3");
    }//GEN-LAST:event_bu3ActionPerformed

    private void bu4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bu4ActionPerformed
        // TODO add your handling code here:
        tf.setText(tf.getText() + "4");
    }//GEN-LAST:event_bu4ActionPerformed

    private void bu5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bu5ActionPerformed
        // TODO add your handling code here:
        tf.setText(tf.getText() + "5");
    }//GEN-LAST:event_bu5ActionPerformed

    private void bu6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bu6ActionPerformed
        // TODO add your handling code here:
        tf.setText(tf.getText() + "6");
    }//GEN-LAST:event_bu6ActionPerformed

    private void bu7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bu7ActionPerformed
        // TODO add your handling code here:
        tf.setText(tf.getText() + "7");
    }//GEN-LAST:event_bu7ActionPerformed

    private void bu8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bu8ActionPerformed
        // TODO add your handling code here:
        tf.setText(tf.getText() + "8");
    }//GEN-LAST:event_bu8ActionPerformed

    private void bu9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bu9ActionPerformed
        // TODO add your handling code here:
        tf.setText(tf.getText() + "9");
    }//GEN-LAST:event_bu9ActionPerformed

    private void buAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buAddActionPerformed
        tf.setText(tf.getText() + "+");
    }//GEN-LAST:event_buAddActionPerformed

    private void buSubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buSubActionPerformed
        tf.setText(tf.getText() + "-");
    }//GEN-LAST:event_buSubActionPerformed

    private void buMultiplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buMultiplyActionPerformed
        tf.setText(tf.getText() + "*");;
    }//GEN-LAST:event_buMultiplyActionPerformed

    private void buDivideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buDivideActionPerformed
        tf.setText(tf.getText() + "/");
    }//GEN-LAST:event_buDivideActionPerformed

    private void buDecimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buDecimalActionPerformed
        tf.setText(tf.getText() + ".");
    }//GEN-LAST:event_buDecimalActionPerformed

    private void buAnsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buAnsActionPerformed
        
        if(!tf.getText().isEmpty()) {
            double result = EvaluateExpression.evaluate(tf.getText());
            tf.setText(result + "");
        }
        
        
    }//GEN-LAST:event_buAnsActionPerformed

    private void buDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buDelActionPerformed
        String s = tf.getText();
        
        if(s.length() > 1){
            tf.setText(s.substring(0, s.length()-1));
        }
        else {
            tf.setText("");
        }
    }//GEN-LAST:event_buDelActionPerformed

    private void buCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buCActionPerformed
        tf.setText("");
    }//GEN-LAST:event_buCActionPerformed

    private void bu0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bu0ActionPerformed
        tf.setText(tf.getText() + "0");
    }//GEN-LAST:event_bu0ActionPerformed

    private void buOpenParenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buOpenParenActionPerformed
        tf.setText(tf.getText() + "(");
    }//GEN-LAST:event_buOpenParenActionPerformed

    private void buClosedParenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buClosedParenActionPerformed
        tf.setText(tf.getText() + ")");
    }//GEN-LAST:event_buClosedParenActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bu0;
    private javax.swing.JButton bu1;
    private javax.swing.JButton bu2;
    private javax.swing.JButton bu3;
    private javax.swing.JButton bu4;
    private javax.swing.JButton bu5;
    private javax.swing.JButton bu6;
    private javax.swing.JButton bu7;
    private javax.swing.JButton bu8;
    private javax.swing.JButton bu9;
    private javax.swing.JButton buAdd;
    private javax.swing.JButton buAns;
    private javax.swing.JButton buC;
    private javax.swing.JButton buClosedParen;
    private javax.swing.JButton buDecimal;
    private javax.swing.JButton buDel;
    private javax.swing.JButton buDivide;
    private javax.swing.JButton buMultiply;
    private javax.swing.JButton buOpenParen;
    private javax.swing.JButton buSub;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField tf;
    // End of variables declaration//GEN-END:variables
}